In [1]:
### Строим логистическую регрессию - расчитываем уровень дохода по признакам
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'C:\MainDataAnalysis\3.Projects\machine learning\netology\2.Классификация Логистическая регрессия и SVM\adult.csv' )
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [4]:
#### Попробуем угадать значение столбца income (>50K, <=50K), по столбцам
#### age, education, occupation, relationship, hours-per-week

In [5]:
# Посмотрим много ли в наших признаках пустых значений
print('Для age пустых строк {}'.format( len( data[ pd.isnull( data['age'] ) ] ) ))
print('Для education пустых строк {}'.format( len( data[ pd.isnull( data['education'] ) ] ) ))
print('Для occupation пустых строк {}'.format( len( data[ pd.isnull( data['occupation'] ) ] ) ))
print('Для relationship пустых строк {}'.format( len( data[ pd.isnull( data['relationship'] ) ] ) ))
print('Для hours-per-week пустых строк {}'.format( len( data[ pd.isnull( data['hours-per-week'] ) ] ) ))
print('Для income пустых строк {}'.format( len( data[ pd.isnull( data['income'] ) ] ) ))
print('Всего строк в наборе {}'.format( len( data ) ))

Для age пустых строк 0
Для education пустых строк 0
Для occupation пустых строк 0
Для relationship пустых строк 0
Для hours-per-week пустых строк 0
Для income пустых строк 0
Всего строк в наборе 48842


In [6]:
# Строк с пустым хначением нет, можем приступить к построению модели

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
# выбираем признаки
selectedColumns = data[ ['age', 'education', 'occupation', 'relationship', 'hours-per-week'] ]

In [9]:
data['education'].unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', 'Doctorate',
       '5th-6th', 'Assoc-voc', '9th', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [10]:
data['occupation'].unique()

array(['Machine-op-inspct', 'Farming-fishing', 'Protective-serv', '?',
       'Other-service', 'Prof-specialty', 'Craft-repair', 'Adm-clerical',
       'Exec-managerial', 'Tech-support', 'Sales', 'Priv-house-serv',
       'Transport-moving', 'Handlers-cleaners', 'Armed-Forces'],
      dtype=object)

In [11]:
data['relationship'].unique()

array(['Own-child', 'Husband', 'Not-in-family', 'Unmarried', 'Wife',
       'Other-relative'], dtype=object)

In [12]:
# столбцы, которые являются категориальными переменными,
# переведем в значения 0 и 1, добавив столбцы с соответствующими названиями
X = pd.get_dummies( selectedColumns, columns = ['education', 'occupation', 'relationship'] )

In [13]:
X

age  hours-per-week  education_10th  education_11th  education_12th  \
0       25              40               0               1               0   
1       38              50               0               0               0   
2       28              40               0               0               0   
3       44              40               0               0               0   
4       18              30               0               0               0   
...    ...             ...             ...             ...             ...   
48837   27              38               0               0               0   
48838   40              40               0               0               0   
48839   58              40               0               0               0   
48840   22              20               0               0               0   
48841   52              40               0               0               0   

       education_1st-4th  education_5th-6th  education_7th-8th  education_9th  \
0                      0                  0                  0              0   
1                      0                  0                  0              0   
2                      0                  0                  0              0   
3                      0                  0                  0              0   
4                      0                  0                  0              0   
...                  ...                ...                ...            ...   
48837                  0                  0                  0              0   
48838                  0                  0                  0              0   
48839                  0                  0                  0              0   
48840                  0                  0                  0              0   
48841                  0                  0                  0              0   

       education_Assoc-acdm  ...  occupation_Protective-serv  \
0                         0  ...                           0   
1                         0  ...                           0   
2                         1  ...                           1   
3                         0  ...                           0   
4                         0  ...                           0   
...                     ...  ...                         ...   
48837                     1  ...                           0   
48838                     0  ...                           0   
48839                     0  ...                           0   
48840                     0  ...                           0   
48841                     0  ...                           0   

       occupation_Sales  occupation_Tech-support  occupation_Transport-moving  \
0                     0                        0                            0   
1                     0                        0                            0   
2                     0                        0                            0   
3                     0                        0                            0   
4                     0                        0                            0   
...                 ...                      ...                          ...   
48837                 0                        1                            0   
48838                 0                        0                            0   
48839                 0                        0                            0   
48840                 0                        0                            0   
48841                 0                        0                            0   

       relationship_Husband  relationship_Not-in-family  \
0                         0                           0   
1                         1                           0   
2                         1                           0   
3                         1                           0   
4                         0                           0   
.

In [14]:
# целевая переменная (столбец income) является категориальной переменной,
# переведем значения столбца в числа, оставив один столбец
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [15]:
le.fit( data['income'] )

LabelEncoder()

In [16]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [17]:
# пример "расшировки" столбца income
le.transform( [ '<=50K', '>50K', '<=50K' ] )

array([0, 1, 0], dtype=int64)

In [18]:
# записываем в переменную y преобразованный столбец income
y = pd.Series( data = le.transform( data['income'] ) )
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int32

In [19]:
# инициализируем модель
model = LogisticRegression()

In [20]:
# обучаем модель
model.fit( X, y )
predictions = model.predict_proba( X )

c:\maindataanalysis\3.projects\machine learning\venv\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [21]:
predictions[:5]

array([[0.99727067, 0.00272933],
       [0.87482638, 0.12517362],
       [0.60515758, 0.39484242],
       [0.68637103, 0.31362897],
       [0.99645547, 0.00354453]])

In [22]:
# сравниваем факт с предсказаниями
# (да, сравнивать предсказания с самими данными не круто, лучше было разбить на обучающую и тестовую выборку)
zip( predictions[:, 1], y )

In [23]:
model.predict(X)

array([0, 0, 0, ..., 0, 0, 1])

In [24]:
model.score(X, y)

0.8315589042217764

In [25]:
# модель предсказывает с точностью 83,155%